services:
  mysql_node-restful_db:
    image: mysql:8.0
    container_name: node_restful_db
    environment:
      MYSQL_DATABASE: node_restful
      MYSQL_USER: node_restful_user
      MYSQL_PASSWORD: your_strong_password
      MYSQL_ROOT_PASSWORD: your_strong_root_password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: